
SELECT PRO.PRODUCT_ID, PRO.PRODUCT_NAME, SUM(AMOUNT* PRICE) AS TOTAL_SALES
FROM FOOD_ORDER AS ORD
    LEFT JOIN FOOD_PRODUCT AS PRO ON ORD.PRODUCT_ID = PRO.PRODUCT_ID
WHERE PRODUCE_DATE BETWEEN '2022-05-01' AND '2022-05-31'
GROUP BY PRO.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRO.PRODUCT_ID ASC