
WITH MOST_REVIEWED_MEM AS (
    SELECT RR.MEMBER_ID, COUNT(*) AS REVEIW_CNT
    FROM REST_REVIEW AS RR
        LEFT JOIN MEMBER_PROFILE AS MEM ON RR.MEMBER_ID = MEM.MEMBER_ID
    GROUP BY RR.MEMBER_ID
    ORDER BY COUNT(*) DESC
    LIMIT 1
)
SELECT 
    MEM.MEMBER_NAME, 
    RR.REVIEW_TEXT, 
    DATE_FORMAT(RR.REVIEW_DATE, "%Y-%m-%d") AS REVIEW_DATE
FROM REST_REVIEW AS RR
    LEFT JOIN MEMBER_PROFILE AS MEM ON RR.MEMBER_ID = MEM.MEMBER_ID
WHERE RR.MEMBER_ID IN (SELECT MEMBER_ID FROM MOST_REVIEWED_MEM) 
ORDER BY RR.REVIEW_DATE ASC, RR.REVIEW_TEXT ASC