
SELECT 
    RE.REST_ID AS REST_ID, 
    INFO.REST_NAME AS REST_NAME,
    INFO.FOOD_TYPE AS FOOD_TYPE,
    INFO.FAVORITES AS FAVORITES,
    INFO.ADDRESS AS ADDRESS,
    ROUND(AVG(RE.REVIEW_SCORE), 2) AS 'SCORE'
FROM REST_INFO AS INFO
    INNER JOIN REST_REVIEW AS RE ON INFO.REST_ID = RE.REST_ID
GROUP BY RE.REST_ID
HAVING INFO.ADDRESS LIKE '서울%'
ORDER BY SCORE DESC, FAVORITES DESC