WITH USER_2021 AS (
    SELECT USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = 2021
),
TOTAL_CNT_2021 AS (
    SELECT COUNT(*) AS TOTAL_CNT FROM USER_2021
)

SELECT 
    YEAR(OS.SALES_DATE) AS YEAR,
    MONTH(OS.SALES_DATE) AS MONTH,
    COUNT(DISTINCT OS.USER_ID) AS PURCHASED_USERS,
    ROUND(
        COUNT(DISTINCT OS.USER_ID) / (SELECT TOTAL_CNT FROM TOTAL_CNT_2021), 
        1
    ) AS PUCHASED_RATIO
FROM ONLINE_SALE OS
JOIN USER_2021 U ON OS.USER_ID = U.USER_ID
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH