
SELECT 
    AP.APNT_NO, 
    PT.PT_NAME, 
    AP.PT_NO, 
    AP.MCDP_CD, 
    DOC.DR_NAME, 
    AP.APNT_YMD
FROM DOCTOR AS DOC
    LEFT JOIN APPOINTMENT AS AP ON DOC.DR_ID = AP.MDDR_ID
    LEFT JOIN PATIENT AS PT ON AP.PT_NO = PT.PT_NO
WHERE APNT_CNCL_YN = 'N' AND 
    DATE(AP.APNT_YMD) = '2022-04-13' AND
    AP.MCDP_CD = 'CS'
ORDER BY AP.APNT_YMD ASC