
WITH FH AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM FIRST_HALF
    GROUP BY FLAVOR
),
JL AS (
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS TOTAL_ORDER
    FROM JULY
    GROUP BY FLAVOR
),
TOTAL AS (
    SELECT FH.FLAVOR, SUM(JL.TOTAL_ORDER + FH.TOTAL_ORDER) AS TOTAL_ORDER
    FROM FH
        LEFT JOIN JL ON FH.FLAVOR =JL.FLAVOR
    GROUP BY FH.FLAVOR
)

SELECT FLAVOR
FROM TOTAL
ORDER BY TOTAL_ORDER DESC
LIMIT 3