-- 코드를 입력하세요

WITH JAN_SALES AS (
    SELECT 
        BOOK_ID, 
        SALES
    FROM BOOK_SALES AS SALES
    WHERE MONTH(SALES_DATE) = 1
            AND YEAR(SALES_DATE) = 2022
)

SELECT 
    BOOK.CATEGORY AS CATEGORY, 
    SUM(SALES) AS TOTAL_SALES
FROM JAN_SALES
    LEFT JOIN BOOK ON JAN_SALES.BOOK_ID = BOOK.BOOK_ID
GROUP BY CATEGORY 
ORDER BY CATEGORY ASC