
SELECT 
    AU.AUTHOR_ID, 
    AU.AUTHOR_NAME, 
    BK.CATEGORY, 
    SUM(SALES*PRICE) AS SALES
FROM BOOK_SALES AS SA
    LEFT JOIN BOOK AS BK ON SA.BOOK_ID = BK.BOOK_ID
    LEFT JOIN AUTHOR AS AU ON BK.AUTHOR_ID = AU.AUTHOR_ID
WHERE SALES_DATE < '2022-02-01'
GROUP BY AU.AUTHOR_ID, CATEGORY
ORDER BY AU.AUTHOR_ID ASC, CATEGORY DESC