-- 코드를 입력하세요
WITH NEW_RENT_HIS AS (
    SELECT 
        CAR.CAR_ID, 
        CAR.CAR_TYPE,
        HISTORY_ID, 
        DATEDIFF(END_DATE, START_DATE) + 1 AS DIFF,
        DAILY_FEE * (DATEDIFF(END_DATE, START_DATE) + 1) AS FEE,
        CASE 
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >=90 THEN '90일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >=30 THEN '30일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >=7 THEN '7일 이상'
            ELSE 0
        END AS DUR
    FROM CAR_RENTAL_COMPANY_CAR AS CAR
        LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HIS ON CAR.CAR_ID = HIS.CAR_ID
    WHERE CAR_TYPE = '트럭'
)

SELECT 
    HISTORY_ID, 
    ROUND(FEE * (100-IFNULL(DISCOUNT_RATE,0))/100,0) AS FEE
FROM NEW_RENT_HIS AS HIS
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS PLAN ON HIS.DUR=PLAN.DURATION_TYPE AND HIS.CAR_TYPE = PLAN.CAR_TYPE
WHERE HIS.CAR_TYPE = '트럭'
ORDER BY FEE DESC, HISTORY_ID DESC