-- 코드를 입력하세요

WITH AVAIL AS (
    SELECT  CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HIS
    WHERE START_DATE <= '2022-10-16' AND '2022-10-16' <= END_DATE
)

SELECT 
    CAR_ID,
    IF (CAR_ID IN (SELECT * FROM AVAIL), '대여중', '대여 가능') AS AVAILABILITY
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
GROUP BY CAR_ID
ORDER BY CAR_ID DESC