
SELECT 
    CAR.CAR_ID, 
    CAR.CAR_TYPE, 
    ROUND(DAILY_FEE * (100-DISCOUNT_RATE)/100 * 30,0) AS FEE
FROM CAR_RENTAL_COMPANY_CAR AS CAR
    LEFT JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS RENT ON CAR.CAR_ID = RENT.CAR_ID
    LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS DIS ON DIS.CAR_TYPE = CAR.CAR_TYPE
WHERE 
    CAR.CAR_TYPE IN ('세단', 'SUV')
    AND CAR.CAR_ID NOT IN (
        SELECT CAR_ID 
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
        WHERE '2022-11-01' <= END_DATE AND START_DATE < '2022-12-01'
    )
    AND DURATION_TYPE LIKE '30일 이상'
GROUP BY CAR_ID
HAVING (500000 <= FEE AND FEE < 2000000)
ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC