-- 코드를 입력하세요
WITH USER_FOUND AS (
    SELECT WRITER_ID, COUNT(*) AS NUM_DIS
    FROM USED_GOODS_BOARD
    GROUP BY WRITER_ID
    HAVING NUM_DIS >= 3
)

SELECT 
    USER_ID, 
    NICKNAME, 
    CONCAT(CITY, ' ', STREET_ADDRESS1, ' ', STREET_ADDRESS2) AS 전체주소,
    CONCAT(SUBSTR(TLNO, 1, 3), '-', SUBSTR(TLNO, 4, 4), '-', SUBSTR(TLNO, 8)) AS 전화번호
FROM USED_GOODS_USER 
WHERE USER_ID IN (SELECT WRITER_ID FROM USER_FOUND)
ORDER BY USER_ID DESC
