-- 코드를 입력하세요
SELECT CONCAT('/home/grep/src/',FILE.BOARD_ID,'/',FILE.FILE_ID,FILE.FILE_NAME,FILE.FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE AS FILE 
WHERE BOARD_ID = (
    SELECT BOARD_ID
    FROM USED_GOODS_BOARD
    ORDER BY VIEWS DESC
    LIMIT 1
)
ORDER BY FILE_ID DESC;