-- 코드를 작성해주세요

SELECT 
    CHILD.ITEM_ID AS ITEM_ID,
    CHILD.ITEM_NAME AS ITEM_NAME,
    CHILD.RARITY AS RARITY
FROM
    ITEM_INFO AS CHILD
    LEFT JOIN ITEM_TREE AS CON ON CHILD.ITEM_ID = CON.PARENT_ITEM_ID
    LEFT JOIN ITEM_INFO AS PAR ON PAR.ITEM_ID = CON.ITEM_ID
WHERE PAR.ITEM_ID IS NULL
ORDER BY ITEM_ID DESC