-- 코드를 작성해주세요

SELECT 
    PAR.ITEM_ID, PAR.ITEM_NAME, PAR.RARITY
FROM ITEM_INFO AS CHILD
    LEFT JOIN ITEM_TREE AS CON ON CHILD.ITEM_ID = CON.PARENT_ITEM_ID
    LEFT JOIN ITEM_INFO AS PAR ON PAR.ITEM_ID = CON.ITEM_ID
WHERE CHILD.RARITY = 'RARE' AND PAR.ITEM_ID IS NOT NULL
ORDER BY PAR.ITEM_ID DESC