-- 코드를 작성해주세요

WITH CODE_IN_NEED AS (
    SELECT SUM(CODE) AS NEED_CODE
    FROM SKILLCODES
    WHERE NAME IN ('Python', 'C#')
)

SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS AS DEV
WHERE DEV.SKILL_CODE & (SELECT * FROM CODE_IN_NEED)
ORDER BY ID