WITH G as (
    SELECT
        EMP_NO,
        AVG(SCORE) AS SCORE
    FROM HR_GRADE
    GROUP BY EMP_NO
)

SELECT 
    G.EMP_NO,
    EMP.EMP_NAME,
    CASE
        WHEN G.SCORE >= 96 THEN 'S'
        WHEN G.SCORE >= 90 THEN 'A'
        WHEN G.SCORE >= 80 THEN 'B'
        ELSE 'C'
    END AS GRADE,
    CASE
        WHEN G.SCORE >= 96 THEN EMP.SAL * 0.2
        WHEN G.SCORE >= 90 THEN EMP.SAL * 0.15
        WHEN G.SCORE >= 80 THEN EMP.SAL * 0.1
        ELSE 0
    END AS BONUS
FROM HR_EMPLOYEES AS EMP 
    LEFT JOIN G ON EMP.EMP_NO = G.EMP_NO
ORDER BY G.EMP_NO ASC