-- 코드를 작성해주세요
WITH SCORE_2022 AS (
    SELECT EMP_NO, SUM(SCORE) AS TOTAL_SCORE 
    FROM HR_GRADE
    WHERE YEAR = 2022
    GROUP BY EMP_NO, YEAR
)

SELECT 
    SCORE_2022.TOTAL_SCORE AS SCORE,
    HR_EMPLOYEES.EMP_NO AS EMP_NO,
    HR_EMPLOYEES.EMP_NAME AS EMP_NAME,
    HR_EMPLOYEES.POSITION AS POSITION, 
    HR_EMPLOYEES.EMAIL AS EMAIL
FROM SCORE_2022 
    LEFT JOIN HR_EMPLOYEES ON SCORE_2022.EMP_NO = HR_EMPLOYEES.EMP_NO
ORDER BY
    SCORE_2022.TOTAL_SCORE DESC
LIMIT 1