
WITH RECURSIVE RNKS AS (
    SELECT ID, PARENT_ID, 1 AS GENERATION
    FROM ECOLI_DATA
    WHERE PARENT_ID IS NULL
    
    UNION ALL
    
    SELECT CHILD.ID, CHILD.PARENT_ID, RNKS.GENERATION+1
    FROM RNKS INNER JOIN ECOLI_DATA AS CHILD ON RNKS.ID = CHILD.PARENT_ID
)

SELECT COUNT(ID) AS COUNT, GENERATION
FROM RNKS
WHERE ID NOT IN (
    SELECT DISTINCT(PARENT_ID)
    FROM RNKS
    WHERE PARENT_ID IS NOT NULL
)
GROUP BY GENERATION
ORDER BY GENERATION
