
With RECURSIVE TIME_TABLE as (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM TIME_TABLE
    WHERE HOUR < 23
)

SELECT TIME_TABLE.HOUR AS 'HOUR', COUNT(OUTS.ANIMAL_ID) AS 'COUNT'
FROM TIME_TABLE
    LEFT JOIN ANIMAL_OUTS as OUTS on HOUR(DATETIME) = TIME_TABLE.HOUR
GROUP BY TIME_TABLE.HOUR
ORDER BY TIME_TABLE.HOUR ASC