-- 코드를 입력하세요
SELECT 
    ANIMAL_ID,
    NAME
FROM (
    SELECT 
        INS.ANIMAL_ID,
        INS.NAME,
        INS.DATETIME as IN_D,
        OUTS.DATETIME as OUT_D,
        DATEDIFF(OUTS.DATETIME, INS.DATETIME) AS PRTC,
        ROW_NUMBER() OVER (ORDER BY DATEDIFF(OUTS.DATETIME, INS.DATETIME) DESC) AS RN
    FROM ANIMAL_INS AS INS
        LEFT JOIN ANIMAL_OUTS AS OUTS ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
) AS T
WHERE RN <= 2