
WITH 
    YOUGURT AS (
        SELECT CART_ID
        FROM CART_PRODUCTS
        WHERE NAME LIKE 'Yogurt'
    ),
    MILK AS (
        SELECT CART_ID
        FROM CART_PRODUCTS
        WHERE NAME LIKE 'Milk'
    )
    
SELECT CART_ID
FROM CART_PRODUCTS
WHERE CART_ID IN (SELECT CART_ID FROM YOUGURT) AND CART_ID IN (SELECT CART_ID FROM MILK)
GROUP BY CART_ID
